language: python
python:
- '3.4'
- '3.5'
- '3.6'
env:
- DOCKER_TESTING_HOST=localhost
- DOCKER_TESTING_PORT=54310
before_install:
- make build-test
- make run-test
install:
- pip install -r requirements-dev.txt
script:
- make tests
