language: python
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip install codecov
- pip install poetry
install:
- poetry install
script:
- poetry run nosetests --with-coverage --cover-package=walli_api
after_success:
- poetry run codecov --gcov-root walli
environment:
  global:
  - FLASK_SECRET=asecretkeyusedfortestingpurposeonly
